---
- hosts: all
  vars:
    env: stagging

  tasks:
    # - ansible.builtin.debug:
    #     msg: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    # - ansible.builtin.set_fact:
    #     env: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    - ansible.builtin.include_vars:
        file: ./vars/git_credentials.yaml

    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    - name: Clone the infrastructure code repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ ansible_env.HOME }}/git-fevermap"
        single_branch: yes
        version: "{{ env }}"

    - name: Create project on Openshift
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ namespace }}"
        state: "{{ state }}"
        api_version: v1
        metadata:
        annotations:
            openshift.io/description: "{{ namespace_description }}"
            openshift.io/display-name: "{{ namespace_display_name }}"

    - name: Create template on Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/template-fevermap.yaml"