---
- hosts: all

  tasks:
    # - ansible.builtin.debug:
    #     msg: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    # - ansible.builtin.set_fact:
    #     env: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    - ansible.builtin.include_vars:
        file: ./vars/git_credentials.yaml

    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    - name: Clone the infrastructure code repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ ansible_env.HOME }}/git-fevermap"
        single_branch: yes
        version: "{{ env }}"

    - name: Copy namespace yaml creation
      ansible.builtin.template:
        src: namespace.yaml.j2
        dest: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"

    - name: Get Openshift projects
      kubernetes.core.k8s_info:
        kind: Project
        api_version: "project.openshift.io/v1"
        label_selectors:
          - "app = {{ application_name }}"
          - "env = {{ env }}"
      register: project_status

    - ansible.builtin.debug:
        var: project_status

    - name: Create Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"

    - name: add label to existing namespace
      kubernetes.core.k8s:
        state: patched
        kind: Namespace
        name: "{{ namespace }}"
        definition:
          metadata:
            labels:
              app: "{{ application_name }}"
              env: "{{ env }}"

    - name: Create template on Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/template-fevermap.yaml"