---
- hosts: all
  vars_files:
    - ./vars/git_credentials.yaml
    - ./vars/registry_io_token.yaml

  tasks:
    - ansible.builtin.debug:
        msg: "{{ awx_webhook_payload.ref.split('/')[2] }}"
      when: env is not defined

    - ansible.builtin.set_fact:
        env: "{{ awx_webhook_payload.ref.split('/')[2] }}"
      when: env is not defined

    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    - name: Clone the infrastructure code repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ ansible_env.HOME }}/git-fevermap"
        single_branch: yes
        version: "{{ env }}"

    - name: Copy namespace yaml creation
      ansible.builtin.template:
        src: namespace.yaml.j2
        dest: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"

    - name: Get Openshift projects
      kubernetes.core.k8s_info:
        kind: Project
        api_version: "project.openshift.io/v1"
        name: "{{ namespace }}"
      register: project_status

    - name: Create Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"
      when: project_status.resources == []

    - name: Create template on Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/template-fevermap.yaml"
        namespace: "{{ namespace }}"

    - name: Process a template in the cluster
      community.okd.openshift_process:
        name: "{{ template_name }}"
        namespace: "{{ namespace }}"
        parameters: "{{ template_parameters }}"
        state: present

    - name: redhat.io pull secret
      kubernetes.core.k8s:
        namespace: "{{ namespace }}"
        state: "{{ state }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            labels:
              app: "{{ application_name }}"
              env: "{{ env }}"
            name: registry-redhat-io-secret
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ redhat_io_pull_token }}"
        
        
