---
- hosts: all

  tasks:
    - ansible.builtin.debug:
        var: awx_webhook_payload.repository.default_branch

    - ansible.builtin.set_fact:
        env: awx_webhook_payload.repository.default_branch
    
    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    # - name: Create project on Openshift
    #   kubernetes.core.k8s:
    #     kind: Namespace
    #     name: "{{ namespace }}"
    #     state: "{{ state }}"
    #     api_version: v1
    #     metadata:
    #       annotations:
    #         openshift.io/description: "{{ namespace_description }}"
    #         openshift.io/display-name: "{{ namespace_display_name }}"
    #       name: "{{ namespace }}"
    