---
- hosts: all
  vars_files:
    - ./vars/{{ env }}.yaml

  tasks:
    - debug:
        var: env
    # - name: Create project on Openshift
    #   kubernetes.core.k8s:
    #     kind: Namespace
    #     name: "{{ namespace }}"
    #     state: "{{ state }}"
    #     api_version: v1
    #     metadata:
    #       annotations:
    #         openshift.io/description: "{{ namespace_description }}"
    #         openshift.io/display-name: "{{ namespace_display_name }}"
    #       name: "{{ namespace }}"
    