---
- hosts: all
  vars:
    env: stagging

  tasks:
    # - ansible.builtin.debug:
    #     msg: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    # - ansible.builtin.set_fact:
    #     env: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    - ansible.builtin.include_vars:
        file: ./vars/git_credentials.yaml

    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    # - command: cat {{ secret_key }}
    #   register: priv_key

    # - ansible.builtin.debug:
    #     var: priv_key.stdout_lines

    # - ansible.builtin.file:
    #     path: "{{ secret_key }}"
    #     mode: 0600

    # - ansible.builtin.shell: eval `ssh-agent -s`
    #   args:
    #     executable: /bin/bash


    # - ansible.builtin.shell: ssh-add {{ secret_key }}
    #   args:
    #     executable: /bin/bash

    - name: Clone the infrastructure code repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ ansible_env.HOME }}/git-fevermap"
        # accept_hostkey: yes
        # key_file: "{{ secret_key }}.pem"
        single_branch: yes
        version: "{{ env }}"

    # - name: Create project on Openshift
    #   kubernetes.core.k8s:
    #     kind: Namespace
    #     name: "{{ namespace }}"
    #     state: "{{ state }}"
    #     api_version: v1
    #     metadata:
    #     annotations:
    #         openshift.io/description: "{{ namespace_description }}"
    #         openshift.io/display-name: "{{ namespace_display_name }}"

    # - name: Create template on Openshift project
    #   kubernetes.core.k8s:
    #     state: "{{ state }}"
    #     src: "{{ ansible_env.HOME }}/template-fevermap.yaml"