---
- hosts: all
  vars:
    env: stagging

  tasks:
    - ansible.builtin.debug:
        msg: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    - ansible.builtin.set_fact:
        env: "{{ awx_webhook_payload.ref.split('/')[2] }}"

    - ansible.builtin.include_vars:
        file: ./vars/git_credentials.yaml

    - ansible.builtin.include_vars:
        file: ./vars/{{ env }}.yaml

    - name: Clone the infrastructure code repository
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ ansible_env.HOME }}/git-fevermap"
        single_branch: yes
        version: "{{ env }}"

    - name: Copy namespace yaml creation
      ansible.builtin.template:
        src: namespace.yaml.j2
        dest: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"

    - name: Create Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/namespace.yaml"

    - name: Create template on Openshift project
      kubernetes.core.k8s:
        state: "{{ state }}"
        src: "{{ ansible_env.HOME }}/git-fevermap/template-fevermap.yaml"