---
namespace: fevermap-{{ env }}
namespace_description: | 
  FeverMap is a mobile application that helps in tracking the spread 
  of coronavirus cases in real-time before people actually get tested.
namespace_display_name: "{{ env }} environment for Fevermap app"